### PR TITLE
Music album & Genre features

### LINKED ISSUE #8: [0.5pt] Member 2 - Create MusicAlbum class
Create MusicAlbum class in a separate .rb file.

### LINKED ISSUE #10: [1pts] Member 2 -Create Genre class
Create Genre class with an association to the Item class (in a separate .rb file).

### LINKED ISSUE #12: [1pt] Member 2 - MusicAlbum class properties  in the constructor
All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.

### LINKED ISSUE #14: [1pt] Member 2 - Genre class properties  in the constructor method
All Genre class properties visible in the diagram should be defined and set up in the constructor method.

### LINKED ISSUE #18: [3pts] Member 2- Implement add_item method in Genre class
Implement methods:

1. add_item method in the Genre class

- should take an instance of the Item class as an input
- should add the input item to the collection of items
- should add self as a property of the item object (by using the correct setter from the item object)

### LINKED ISSUE #24: [3pts] Member 2- Implement can_be_archived?() method in Genre class
can_be_archived?() in the MusicAlbum class
- should override the method from the parent class
- should return true if parent's method returns true AND if on_spotify equals true
- otherwise, it should return false

### LINKED ISSUE #30: [3pts] Member 2 - Add options
The following options should be available:
- List all music albums
- List all genres (e.g 'Comedy', 'Thriller')
- Add a music album

### LINKED ISSUE #34: [3pts] Member 2- Save data
All data should be preserved by saving collections in .json files.

### PR DESCRIPTION
**Pull request by souad988**
# Ruby group capstone - Catalog of my things: 

### Team member #2
- Create MusicAlbum class in a separate .rb file.
- Create Genre class with an association to the Item class (in a separate .rb file).
- All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.
- All Genre class properties visible in the diagram should be defined and set up in the constructor method.
- Implement methods:
    - add_item method in the Genre class
        - should take an instance of the Item class as an input
        - should add the input item to the collection of items
        - should add self as a property of the item object (by using the correct setter from the item object)
    - can_be_archived?() in the MusicAlbum class
        - should override the method from the parent class
        - should return true if parent's method returns true AND if on_spotify equals true
        - otherwise, it should return false
 - The following options should be available:
    - List all music albums
    - List all genres (e.g 'Comedy', 'Thriller')
    - Add a music album
 - All data should be preserved by saving collections in .json files.
## Note
-we need to discuss how to solve "C: Metrics/ParameterLists: Avoid parameter lists longer than 5 parameters." linter error tomorrow morning

### CODE REVIEW

**Comment by RayhanTabase** [comment]
@souad988  Please resolve merge conflicts

@RayhanTabase  i resolved the conflict would you please run the code and test the features,

**Comment by RayhanTabase** [comment]
@souad988 There is no name variable in the requirements, please could you inform me what the purpose of that variable is?

**Comment by souad988** [comment]
> @souad988 There is no name variable in the requirements, please could you inform me what the purpose of that variable is?

Hi @RayhanTabase would you please highlight the line of code you want me to clarify about

**Review by RayhanTabase — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hi @souad988 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

well-1

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
------

**Comment by souad988** [comment]
> # STATUS: APPROVED 🟢 👏
> Hi @souad988 ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ## TO HIGHLIGHT:
> * Your project is professional 💯
> * Your repo is professional 💯
> * Well structured files 💯
> * You set up linter files and no errors. 💯
> 
> well-1 [ ](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif) well-1 [ ](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)
> 
> Cheers and Happy coding!👏👏👏
> 
> ## Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> Please, remember to tag me in your question so I can receive the notification.

thanks @RayhanTabase

**Pull request merged**
